version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: baixada_santista_news
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d baixada_santista_news"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:password@postgres:5432/baixada_santista_news
      - JWT_SECRET=your-secret-jwt-key
      - NEXTAUTH_SECRET=your-secret
      - ACCESS_TOKEN_SECRET=your-secret-access-token
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        npm run db:generate &&
        npm run db:push &&
        npm run dev
      "

volumes:
  postgres_data: